### ISSUE TITLE
Scaled launch checklist

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#186]
# Critical
- [x] Backend and frontend revision and migration
- [x] #202
- [x] Update email for backend #171 
- [x] #227
- [x] Improve user bio on profile: website, blurb  #129 #99 #76 
- [x] Invite code provisioning and distribution system -> #95 #63 
- [x] #201
- [x] #196
- [x] #197
- [x] Ability to delete or deactivate an account -> #90 

# Less critical
- [ ] #55
- [ ] Remove "all users" page, but make sure there's a reasonable way to explore
- [ ] Ability to send email announcements #97
